/**
 * FlowTalos — Storacha IPFS Audit Logger
 * ========================================
 * Creates an immutable, content-addressed proof of the AI Agent's reasoning
 * by uploading it to the Storacha network (Filecoin/IPFS).
 *
 * The resulting CID (Content Identifier) is embedded in the on-chain Cadence
 * transaction, creating a permanent, verifiable link between the AI's decision
 * and its execution — this is the "Glass-Box" transparency mechanism.
 *
 * Fallback Strategy (3-tier, never crashes):
 *   Tier 1: Full Storacha upload → Real pinned IPFS CID
 *   Tier 2: Local SHA-256 CID    → Same algorithm as IPFS, computed locally
 *   Tier 3: Emergency hash       → Raw crypto.createHash('sha256') last resort
 *
 * Communication Protocol:
 *   Outputs CIDs to stdout using the `__CID_OUTPUT__:<cid>` marker format,
 *   which the Python AI Agent parses from subprocess output.
 *
 * Usage (called by Python AI Agent via subprocess):
 *   $ npx ts-node src/index.ts <path_to_json_file>
 *
 * @module storacha-logger
 * @author FlowTalos Team
 */

import { create } from '@web3-storage/w3up-client'
import * as dotenv from 'dotenv';
import { sha256 } from 'multiformats/hashes/sha2';
import { CID } from 'multiformats/cid';
import * as raw from 'multiformats/codecs/raw';

dotenv.config();


/**
 * Computes a real content-addressed CID (CIDv1) from raw data using SHA-256.
 * This is the same algorithm IPFS uses — each unique input produces a unique CID.
 */
async function computeContentCID(data: string): Promise<string> {
    const encoder = new TextEncoder();
    const bytes = encoder.encode(data);
    const hash = await sha256.digest(bytes);
    const cid = CID.create(1, raw.code, hash);
    return cid.toString();
}

/**
 * Uploads a text-based reasoning string generated by Synapse AI to Storacha.
 * Falls back to local CID computation when credentials are not configured.
 * @param reasoningText The explanation from the AI agent.
 * @returns The IPFS CID strictly tying the execution to this reasoning payload.
 */
async function pinReasoningToStoracha(reasoningText: string): Promise<string> {
    console.log("Initializing Storacha client...");
    const client = await create();

    const auditObject = {
        app: "FlowTalos Glass-Box Agent",
        timestamp: new Date().toISOString(),
        reasoning: reasoningText,
    };

    const jsonPayload = JSON.stringify(auditObject, null, 2);

    // Serialize to Blob / File
    const blob = new Blob([jsonPayload], { type: 'application/json' });
    const file = new File([blob], 'flowtalos-reasoning-log.json');

    console.log("Uploading file to Storacha (Filecoin/IPFS)...");

    try {
        const directoryCid = await client.uploadDirectory([file]);
        console.log(`\n[✔] Upload Successful! Auditable CID: ${directoryCid.toString()}`);
        return directoryCid.toString();
    } catch (error) {
        console.error("Failed to upload to Storacha network, computing local CID...");
        // Compute a real content-addressed CID locally
        const localCid = await computeContentCID(jsonPayload);
        console.log(`[✔] Local CID computed: ${localCid}`);
        return localCid;
    }
}

// ---------------------------------------------------------
// File Execution (Input from Python backend)
// ---------------------------------------------------------

import * as fs from 'fs';
import * as pathModule from 'path';

async function main() {
    const args = process.argv.slice(2);
    if (args.length < 1) {
        console.error("Usage: npx ts-node src/index.ts <path_to_json_file>");
        process.exit(1);
    }

    const filePath = args[0];

    // Security: Validate file path to prevent path traversal attacks
    const resolvedPath = pathModule.resolve(filePath);
    const allowedDirs = [require('os').tmpdir(), process.cwd()];
    if (!allowedDirs.some(dir => resolvedPath.startsWith(dir))) {
        console.error(`[Security] Rejected path outside allowed directories: ${filePath}`);
        process.exit(1);
    }

    if (!fs.existsSync(resolvedPath)) {
        console.error(`File not found: ${resolvedPath}`);
        process.exit(1);
    }

    // Security: Reject oversized files to prevent OOM (max 10MB)
    const MAX_FILE_SIZE = 10 * 1024 * 1024;
    const fileStats = fs.statSync(resolvedPath);
    if (fileStats.size > MAX_FILE_SIZE) {
        console.error(`[Security] File exceeds 10MB limit: ${fileStats.size} bytes`);
        process.exit(1);
    }

    let fileContent: string;
    try {
        fileContent = fs.readFileSync(resolvedPath, 'utf-8');
        // Validate JSON is parseable (catch malformed input from Python)
        JSON.parse(fileContent);
    } catch (parseErr: unknown) {
        const errMsg = parseErr instanceof Error ? parseErr.message : 'Unknown parse error';
        console.error(`⚠ [Storacha] Input file is not valid JSON: ${errMsg}`);
        console.log("Computing CID from raw file content as fallback...");
        fileContent = fs.readFileSync(resolvedPath, 'utf-8');
        // Still compute a CID from the raw content
        const fallbackCid = await computeContentCID(fileContent);
        console.log(`[✔] Fallback CID (raw content): ${fallbackCid}`);
        console.log(`__CID_OUTPUT__:${fallbackCid}`);
        return;
    }

    try {
        if (!process.env.STORACHA_EMAIL_ADDRESS) {
            console.log("\n⚠ [Storacha] No credentials found. Computing real content-addressed CID locally...");

            // Build the same audit object for consistent CID computation
            const auditObject = {
                app: "FlowTalos Glass-Box Agent",
                timestamp: new Date().toISOString(),
                reasoning: fileContent,
            };
            const jsonPayload = JSON.stringify(auditObject, null, 2);

            // Compute a REAL unique CID from the actual content (SHA-256 + CIDv1)
            const realCid = await computeContentCID(jsonPayload);
            console.log(`[✔] Real Content-Addressed CID: ${realCid}`);
            console.log(`__CID_OUTPUT__:${realCid}`);
            return;
        }

        // Full Storacha upload with credentials
        const cid = await pinReasoningToStoracha(fileContent);
        console.log(`__CID_OUTPUT__:${cid}`);

    } catch (err: unknown) {
        const errMsg = err instanceof Error ? err.message : String(err);
        console.error("⚠ Upload failed:", errMsg);
        console.log("Computing emergency fallback CID from content...");
        // NEVER exit(1) — always output a CID so the Python pipeline doesn't break
        try {
            const emergencyCid = await computeContentCID(fileContent);
            console.log(`[✔] Emergency Fallback CID: ${emergencyCid}`);
            console.log(`__CID_OUTPUT__:${emergencyCid}`);
        } catch {
            // Absolute last resort: deterministic hash
            const crypto = require('crypto');
            const lastResortHash = crypto.createHash('sha256').update(fileContent).digest('hex');
            const lastResortCid = `bafyemergency${lastResortHash.slice(0, 48)}`;
            console.log(`[✔] Last-Resort CID: ${lastResortCid}`);
            console.log(`__CID_OUTPUT__:${lastResortCid}`);
        }
    }
}

main();

